create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  path text not null check (char_length(path) between 1 and 500),
  referrer text check (referrer is null or char_length(referrer) <= 255),
  device text not null check (device in ('mobile', 'tablet', 'desktop')),
  source text,
  medium text,
  campaign text,
  content text,
  created_at timestamptz not null default now()
);

create index if not exists page_views_created_at_idx on public.page_views (created_at desc);
create index if not exists page_views_visitor_id_idx on public.page_views (visitor_id);
create index if not exists page_views_path_idx on public.page_views (path);

alter table public.page_views enable row level security;

-- Page views are written and read only by Kuvlo's server-side service role.
-- Visitors and normal signed-in accounts never receive direct table access.
revoke all on table public.page_views from anon, authenticated;
grant all on table public.page_views to service_role;

alter table public.page_views add column if not exists source text;
alter table public.page_views add column if not exists medium text;
alter table public.page_views add column if not exists campaign text;
alter table public.page_views add column if not exists content text;
